version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  backend:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    env_file:
      - ./server/.env
  frontend:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - backend
volumes:
  postgres_data:
