version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trello
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/trello
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - backend
volumes:
  postgres_data:
